sudo: false
language: node_js
node_js:
  - "8"
  - "6"
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
install:
  - npm install
script:
  - npm test
